---
version: '3'

services:
  ccd-definition-designer-api:
    build:
      context: .
    image: hmcts/ccd-definition-designer-api
    environment:
      - DEFINITION_DESIGNER_DB_HOST=ccd-definition-designer-database
      - DEFINITION_DESIGNER_DB_PORT=5432
      - DEFINITION_DESIGNER_DB_USERNAME
      - DEFINITION_DESIGNER_DB_PASSWORD
      - DEFINITION_DESIGNER_IDAM_KEY
      - DEFINITION_DESIGNER_S2S_AUTHORISED_SERVICES=ccd_admin,ccd_gw
      - USER_PROFILE_HOST
      - IDAM_USER_URL
      - IDAM_S2S_URL
      - REFORM_SERVICE_NAME=ccd-definition-designer-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
    ports:
      - 4454:4454
    depends_on:
      - ccd-definition-designer-database
    links:
      - ccd-definition-designer-database

  ccd-definition-designer-database:
    build:
      context: docker/database
    image: hmcts/ccd-definition-designer-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DEFINITION_DESIGNER_DB_USERNAME
      - DEFINITION_DESIGNER_DB_PASSWORD
    ports:
      - 5453:5432
    volumes:
      - ccd-definition-designer-database-data:/var/lib/postgresql/data

volumes:
  ccd-definition-designer-database-data:
